apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-proxy
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
  ports:
    - port: 80
      targetport: 80
      protocol: TCP
  selector:
      app: nginx
      
  
